Repository IBMa/equal-access, pull requests merged in 2023-01, with the labels that each got.

#1129 Fix issues related to aria-autocomplete in a combobox component
  accessibility-checker-engine/help-v4/en-US/combobox_autocomplete.html
  accessibility-checker-engine/src/v4/rules/combobox_autocomplete.ts
  accessibility-checker-engine/src/v4/rules/combobox_focusable_elements.ts
  accessibility-checker-engine/test/v2/checker/accessibility/rules/combobox_autocomplete_ruleunit/popup-autocomplete.html
  accessibility-checker-engine/test/v2/checker/accessibility/rules/combobox_autocomplete_ruleunit/popup-child-autocomplete.html
Labels: Ready for QA

#1198 Fix color contrast issue for the content directly added to a shadow DOM
  accessibility-checker-engine/src/v2/checker/accessibility/util/legacy.ts
  accessibility-checker-engine/src/v4/rules/IBMA_Color_Contrast_WCAG2AA.ts
  accessibility-checker-engine/test/v2/checker/accessibility/rules/IBMA_Color_Contrast_WCAG2AA_ruleunit/Shadow.html
  accessibility-checker-engine/test/v2/checker/accessibility/rules/IBMA_Color_Contrast_WCAG2AA_ruleunit/act_fail_1.html
  accessibility-checker-engine/test/v2/checker/accessibility/rules/IBMA_Color_Contrast_WCAG2AA_ruleunit/act_fail_10.html
  accessibility-checker-engine/test/v2/checker/accessibility/rules/IBMA_Color_Contrast_WCAG2AA_ruleunit/act_fail_2.html
  accessibility-checker-engine/test/v2/checker/accessibility/rules/IBMA_Color_Contrast_WCAG2AA_ruleunit/act_fail_3.html
  accessibility-checker-engine/test/v2/checker/accessibility/rules/IBMA_Color_Contrast_WCAG2AA_ruleunit/act_fail_4.html
  accessibility-checker-engine/test/v2/checker/accessibility/rules/IBMA_Color_Contrast_WCAG2AA_ruleunit/act_fail_5.html
  accessibility-checker-engine/test/v2/checker/accessibility/rules/IBMA_Color_Contrast_WCAG2AA_ruleunit/act_fail_6.html
  accessibility-checker-engine/test/v2/checker/accessibility/rules/IBMA_Color_Contrast_WCAG2AA_ruleunit/act_fail_7.html
  accessibility-checker-engine/test/v2/checker/accessibility/rules/IBMA_Color_Contrast_WCAG2AA_ruleunit/act_fail_8.html
  accessibility-checker-engine/test/v2/checker/accessibility/rules/IBMA_Color_Contrast_WCAG2AA_ruleunit/act_fail_9.html
  accessibility-checker-engine/test/v2/checker/accessibility/rules/IBMA_Color_Contrast_WCAG2AA_ruleunit/act_inapplicable_1.html
  accessibility-checker-engine/test/v2/checker/accessibility/rules/IBMA_Color_Contrast_WCAG2AA_ruleunit/act_inapplicable_10.html
  accessibility-checker-engine/test/v2/checker/accessibility/rules/IBMA_Color_Contrast_WCAG2AA_ruleunit/act_inapplicable_11.html
  accessibility-checker-engine/test/v2/checker/accessibility/rules/IBMA_Color_Contrast_WCAG2AA_ruleunit/act_inapplicable_2.html
  accessibility-checker-engine/test/v2/checker/accessibility/rules/IBMA_Color_Contrast_WCAG2AA_ruleunit/act_inapplicable_3.html
  accessibility-checker-engine/test/v2/checker/accessibility/rules/IBMA_Color_Contrast_WCAG2AA_ruleunit/act_inapplicable_4.html
  accessibility-checker-engine/test/v2/checker/accessibility/rules/IBMA_Color_Contrast_WCAG2AA_ruleunit/act_inapplicable_5.html
  accessibility-checker-engine/test/v2/checker/accessibility/rules/IBMA_Color_Contrast_WCAG2AA_ruleunit/act_inapplicable_6.html
  accessibility-checker-engine/test/v2/checker/accessibility/rules/IBMA_Color_Contrast_WCAG2AA_ruleunit/act_inapplicable_7.html
  accessibility-checker-engine/test/v2/checker/accessibility/rules/IBMA_Color_Contrast_WCAG2AA_ruleunit/act_inapplicable_8.html
  accessibility-checker-engine/test/v2/checker/accessibility/rules/IBMA_Color_Contrast_WCAG2AA_ruleunit/act_inapplicable_9.html
  accessibility-checker-engine/test/v2/checker/accessibility/rules/IBMA_Color_Contrast_WCAG2AA_ruleunit/act_pass_1.html
  accessibility-checker-engine/test/v2/checker/accessibility/rules/IBMA_Color_Contrast_WCAG2AA_ruleunit/act_pass_10.html
  accessibility-checker-engine/test/v2/checker/accessibility/rules/IBMA_Color_Contrast_WCAG2AA_ruleunit/act_pass_11.html
  accessibility-checker-engine/test/v2/checker/accessibility/rules/IBMA_Color_Contrast_WCAG2AA_ruleunit/act_pass_2.html
  accessibility-checker-engine/test/v2/checker/accessibility/rules/IBMA_Color_Contrast_WCAG2AA_ruleunit/act_pass_3.html
  accessibility-checker-engine/test/v2/checker/accessibility/rules/IBMA_Color_Contrast_WCAG2AA_ruleunit/act_pass_4.html
  accessibility-checker-engine/test/v2/checker/accessibility/rules/IBMA_Color_Contrast_WCAG2AA_ruleunit/act_pass_5.html
  accessibility-checker-engine/test/v2/checker/accessibility/rules/IBMA_Color_Contrast_WCAG2AA_ruleunit/act_pass_6.html
  accessibility-checker-engine/test/v2/checker/accessibility/rules/IBMA_Color_Contrast_WCAG2AA_ruleunit/act_pass_7.html
  accessibility-checker-engine/test/v2/checker/accessibility/rules/IBMA_Color_Contrast_WCAG2AA_ruleunit/act_pass_8.html
  accessibility-checker-engine/test/v2/checker/accessibility/rules/IBMA_Color_Contrast_WCAG2AA_ruleunit/act_pass_9.html
Labels: Ready for QA

#1223 Fixed Keyboard mode visualization if the user zooms the web page
  accessibility-checker-extension/package-lock.json
  accessibility-checker-extension/src/ts/contentScripts/draw.ts
  cypress-accessibility-checker/package-lock.json
  report-react/package-lock.json
  rule-server/package-lock.json
Labels: Ready for QA

#1224 Fix the issue related to color contrast not processing transparency correctly
  accessibility-checker-engine/src/v2/checker/accessibility/util/legacy.ts
  accessibility-checker-engine/src/v2/dom/ColorUtil.ts
  accessibility-checker-engine/src/v4/rules/IBMA_Color_Contrast_WCAG2AA.ts
  accessibility-checker-engine/test/v2/checker/accessibility/rules/IBMA_Color_Contrast_WCAG2AA_ruleunit/color_with_transparency.html
Labels: Ready for QA

#1190 Fix issue related to object alternative text check when an object has child content
  accessibility-checker-engine/help-v4/en-US/WCAG20_Object_HasText.html
  accessibility-checker-engine/src/v4/rules/WCAG20_Object_HasText.ts
  accessibility-checker-engine/test/v2/checker/accessibility/rules/WCAG20_Object_HasText_ruleunit/act_fail_1.html
  accessibility-checker-engine/test/v2/checker/accessibility/rules/WCAG20_Object_HasText_ruleunit/act_fail_2.html
  accessibility-checker-engine/test/v2/checker/accessibility/rules/WCAG20_Object_HasText_ruleunit/act_fail_3.html
  accessibility-checker-engine/test/v2/checker/accessibility/rules/WCAG20_Object_HasText_ruleunit/act_fail_4.html
  accessibility-checker-engine/test/v2/checker/accessibility/rules/WCAG20_Object_HasText_ruleunit/act_fail_5.html
  accessibility-checker-engine/test/v2/checker/accessibility/rules/WCAG20_Object_HasText_ruleunit/act_fail_6.html
  accessibility-checker-engine/test/v2/checker/accessibility/rules/WCAG20_Object_HasText_ruleunit/act_implicable_1.html
  accessibility-checker-engine/test/v2/checker/accessibility/rules/WCAG20_Object_HasText_ruleunit/act_implicable_2.html
  accessibility-checker-engine/test/v2/checker/accessibility/rules/WCAG20_Object_HasText_ruleunit/act_implicable_3.html
  accessibility-checker-engine/test/v2/checker/accessibility/rules/WCAG20_Object_HasText_ruleunit/act_implicable_4.html
  accessibility-checker-engine/test/v2/checker/accessibility/rules/WCAG20_Object_HasText_ruleunit/act_implicable_5.html
  accessibility-checker-engine/test/v2/checker/accessibility/rules/WCAG20_Object_HasText_ruleunit/act_implicable_6.html
  accessibility-checker-engine/test/v2/checker/accessibility/rules/WCAG20_Object_HasText_ruleunit/act_implicable_7.html
  accessibility-checker-engine/test/v2/checker/accessibility/rules/WCAG20_Object_HasText_ruleunit/act_implicable_8.html
  accessibility-checker-engine/test/v2/checker/accessibility/rules/WCAG20_Object_HasText_ruleunit/act_pass_1.html
  accessibility-checker-engine/test/v2/checker/accessibility/rules/WCAG20_Object_HasText_ruleunit/act_pass_2.html
  accessibility-checker-engine/test/v2/checker/accessibility/rules/WCAG20_Object_HasText_ruleunit/act_pass_3.html
  accessibility-checker-engine/test/v2/checker/accessibility/rules/WCAG20_Object_HasText_ruleunit/act_pass_4.html
Labels: engine, SME, Ready for QA

#1234 Add FAQ regarding Content Security Policies
  accessibility-checker/src/README.md
Labels: Ready for QA

#1232 Add engine and tool support to allow rule id refactoring without updating baselines
  accessibility-checker-engine/README-RULES.md
  accessibility-checker-engine/src/v4/api/IRule.ts
  accessibility-checker/src-ts/lib/ACEngineManager.ts
  accessibility-checker/src-ts/lib/ACReportManager.ts
  accessibility-checker/src-ts/lib/api/IEngine.ts
  accessibility-checker/test/mocha/aChecker.Fast/aChecker.Baselines/aChecker.Baseline.test.js
  cypress-accessibility-checker/src/lib/ACTasks.js
  karma-accessibility-checker/src/lib/ACHelper.js
Labels: Ready for QA

#1240 fix (Checker packages): Fix error and crash due to custom cacheFolder in achecker.yml
  accessibility-checker/src-ts/lib/ACEngineManager.ts
Labels: node-accessibility-checker, Ready for QA
